# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
#include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
# linter:
#   rules:
#     - prefer_single_quotes

analyzer:
  errors:
    prefer_single_quotes: ignore
    unnecessary_this: ignore
    unused_local_variable: ignore
    omit_local_variable_types: ignore
    todo: ignore
    must_be_immutable: ignore
#   exclude:
#     - path/to/excluded/files/**
