// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

class PangolinX {
  /// Holds the Dynamic library.
  final ffi.DynamicLibrary _dylib;

  /// The symbols are looked up in [dynamicLibrary].
  PangolinX(ffi.DynamicLibrary dynamicLibrary) : _dylib = dynamicLibrary;

  int init_window_manager() {
    _init_window_manager ??= _dylib.lookupFunction<_c_init_window_manager,
        _dart_init_window_manager>('init_window_manager');
    return _init_window_manager();
  }

  _dart_init_window_manager _init_window_manager;
}

typedef _c_init_window_manager = ffi.Int32 Function();

typedef _dart_init_window_manager = int Function();
