import 'calculator.dart';
import 'package:GeneratedApp/widgets/cards.dart';
import 'developer.dart';
import 'editor.dart';
import 'monitor.dart';
import 'terminal.dart';
import 'welcome.dart';
import '../settings.dart';
import '../themes/main.dart';
