name: "Dart analyzer"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  dart: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - uses: invertase/github-action-dart-analyzer@v1
        with:
          # (Optional) Treat info level issues as fatal.
          fatal-infos: false

          # (Optional) Treat warning level issues as fatal
          # (defaults to true).
          fatal-warnings: false

          # (Optional) Whether to add annotations to GitHub actions summary / PR
          # review files.
          # (defaults to true).
          annotate: true

          # (Optional) If set to true only annotations will be created and the
          # GitHub action itself will not fail on Dart analyzer problems. 
          # (defaults to false).
          annotate-only: false

          # (Optional) The working directory to run the Dart analyzer in 
          # (defaults to `./`).
          working-directory: ./
